### ISSUE TITLE
errors when execute initdb.sh

### ISSUE THREAD

**Issue by mjali** [Andre0991/opengts-install-ubuntu#1]
hy, when i type the command 

bin/initdb.sh -rootUser=root -rootPass='password' 

i got this : 

Version: 2.5.9
[ERROR|DBAdmin.execCommands:940] SQLException message: Access denied for user 'root'@'localhost' (using password: YES)
[ERROR|DBAdmin.execCommands:941] ==> SQLException: DB create error [jdbc:mysql://localhost:3306/]
[ERROR|DBAdmin.execCommands:941] Message:   Access denied for user 'root'@'localhost' (using password: YES)
[ERROR|DBAdmin.execCommands:941] SQLState:  28000
[ERROR|DBAdmin.execCommands:941] ErrorCode: 1045
[DBAdmin.execCommands:941] java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
    at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
    at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2239)
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270)
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:215)
    at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
    at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
    at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:760)
    at org.opengts.dbtools.DBConnection._executeUpdate(DBConnection.java:1014)
    at org.opengts.dbtools.DBConnection.executeUpdate(DBConnection.java:969)
    at org.opengts.dbtools.DBConnection.executeUpdate(DBConnection.java:950)
    at org.opengts.dbtools.DBProvider.createDatabase(DBProvider.java:1699)
    at org.opengts.dbtools.DBAdmin.execCommands(DBAdmin.java:929)
    at org.opengts.db.DBConfig._main(DBConfig.java:1797)
    at org.opengts.db.DBConfig.main(DBConfig.java:1912)

**Comment by Andre0991** [comment]
I suspect that the provided combination of user and password is invalid. Please confirm whether you can login by executing `mysql -u root -p`.
